# Generated by Django 4.1.5 on 2023-01-08 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_poll_answer_poll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_answer',
            name='user',
            field=models.CharField(default='pbgp', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='id_user',
            field=models.IntegerField(auto_created=True, default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='poll_question',
            name='id_poll',
            field=models.UUIDField(default=uuid.UUID('c5140b77-31e3-453e-8b30-44cc9cad072b'), primary_key=True, serialize=False),
        ),
    ]
