# Generated by Django 4.1.5 on 2023-01-08 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0003_poll_answer_user_usermodel_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_question',
            name='id_poll',
            field=models.UUIDField(default=uuid.UUID('9c179c8f-84df-44f7-b747-114ac4f02210'), primary_key=True, serialize=False),
        ),
    ]
