# Generated by Django 4.1.5 on 2023-01-08 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0004_alter_poll_question_id_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_question',
            name='user',
            field=models.CharField(default='pbgp', max_length=100),
        ),
        migrations.AlterField(
            model_name='poll_question',
            name='id_poll',
            field=models.UUIDField(default=uuid.UUID('82bd55f9-d930-4f67-ae54-d0c2283f8d62'), primary_key=True, serialize=False),
        ),
    ]
